program: sweeps.py
method: bayes
metric:
  name: test_loss
  goal: minimize
parameters:
  patch_size:
    values: [7, 14, 28]
  embed_dim:
    values: [16, 32, 64, 128]
  encoder_layers:
    values: [2, 4, 6, 8]
  decoder_layers:
    values: [2, 4, 6, 8]
  attention_heads:
    values: [1, 2, 4]
  batch_size:
    values: [16, 32, 64]
  lr:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.001
